mysite/cards/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
]

mysite/mysite/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers
from .api import UserViewSet
from polls.api import QuestionViewSet,ChoiseViewSet
from cards.api import CardViewSet
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'questions',QuestionViewSet)
router.register(r'choises',ChoiseViewSet)
router.register(r'cards',CardViewSet)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cards/', include('cards.urls', namespace="cards")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/cards/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Card(models.Model):
	owner=models.ForeignKey(User)
	url=models.URLField()
	name=models.CharField(max_length=6)
	image=models.ImageField()
	media_type=models.CharField(max_length=32)
	created_at=models.DateTimeField('created at')

	def __repr__(self):
		return '<{}-{}>'.format(self.pk,self.name)

	def __str__(self):              # __unicode__ on Python 2
		return self.name

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.
class Question(models.Model):
	question_text=models.CharField(max_length=200)
	pub_date=models.DateTimeField('date published')

	def __repr__(self):
		return '<{}-{}>'.format(self.pk,self.question_text)

	def __str__(self):              # __unicode__ on Python 2
		return self.question_text

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'

class Choise(models.Model):
	question= models.ForeignKey(Question,related_name='choises')
	choise_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):              # __unicode__ on Python 2
		return self.choise_text

mysite/cards/views.py
from django.shortcuts import render
from .models import Card
from django.views import generic
from django.core.urlresolvers import reverse

class IndexView(generic.ListView):
    template_name = 'cards/index.html'
    context_object_name = 'latest_cards_list'

    def get_queryset(self):
        """Return the last 20 cards."""
        return Card.objects.order_by('-created_at')[:20]


class DetailView(generic.DetailView):
    model = Card
    template_name = 'cards/detail.html'

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Choise, Question
from django.http import Http404
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]



class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choise = p.choise_set.get(pk=request.POST['choise'])
    except (KeyError, Choise.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choise.votes += 1
        selected_choise.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

mysite/cards/templates/cards/detail.html
<h1>Name:{{ card.name }}</h1>
<h1>URL:<a href="{{card.url}}">{{card.url}}</a></h1>
<h1>Content:<a href="{{card.image.url}}">{{card.image}}</a></h1>
<h1>Media Type:{{card.media_type}}</h1>
<h1>Created at:{{card.created_at}}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

mysite/cards/templates/cards/index.html
{% if latest_cards_list %}
    <ul>
    {% for card in latest_cards_list %}
       <li><a href="{% url 'cards:detail' card.id %}">{{ card.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No cards are available.</p>
{% endif %}

mysite/cards/templates/index.html
{% if latest_question_list %}
    <ul>
    {% for card in latest_card_list %}
       <li><a href="{% url 'cards:detail' card.id %}">{{ card.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No cards are available.</p>
{% endif %}

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choise in question.choise_set.all %}
    <input type="radio" name="choise" id="choise{{ forloop.counter }}" value="{{ choise.id }}" />
    <label for="choise{{ forloop.counter }}">{{ choise.choise_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
       <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choise in question.choise_set.all %}
    <li>{{ choise.choise_text }} -- {{ choise.votes }} vote{{ choise.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>